language: cpp

matrix:
  include:
    # - os: linux
    #   dist: xenial
    #   sudo: true
    #   compiler: clang

    - os: windows

install:
  - curl -fSL https://github.com/CRYTEK/CRYENGINE/releases/download/5.5.2/CRYENGINE_v5.5.2_SDKs.zip -o sdks.zip
  - 7z e sdks.zip
  - choco install ninja

script:
  - Tools/CMake/Win32/bin/cmake -DCMAKE_BUILD_TYPE=Profile -BCMake/win_x64_profile -GNinja
  - Tools/CMake/Win32/bin/cmake --build CMake/win_x64_profile