language: cpp

matrix:
  include:
    # - os: linux
    #   dist: xenial
    #   sudo: true
    #   compiler: clang

    - os: windows

install:
  - download_sdks
  - choco install ninja

script:
  - Tools/CMake/Win32/bin/cmake -DCMAKE_BUILD_TYPE=Profile -BCMake/win_x64_profile -GNinja
  - Tools/CMake/Win32/bin/cmake --build CMake/win_x64_profile