language: cpp
compiler: clang

matrix:
  include:
    # - os: linux
    #   dist: xenial
    #   sudo: true
    #   compiler: clang

    - os: windows

install:
  - pwd
  - ./download_sdks
  - choco install ninja

script:
  - Tools/CMake/Win32/bin/cmake.exe -DCMAKE_BUILD_TYPE=Profile -BCMake/win_x64_profile -GNinja
  - Tools/CMake/Win32/bin/cmake.exe --build CMake/win_x64_profile