language: cpp
compiler: clang

cache:
  directories:
  - Code/SDKs

matrix:
  include:
    # - os: linux
    #   dist: xenial
    #   sudo: true
    #   compiler: clang

    - name: "MSVC on Windows"
      os: windows

install:
  - pwd
  - mkdir -p Code/SDKs
  - if [ ! "$(ls -A Code/SDKs)" ]; then ./download_sdks; fi
  - choco install ninja

script:
  - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && Tools\CMake\Win32\bin\cmake.exe -DOPTION_SANDBOX=OFF -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_BUILD_TYPE=Profile -BCMake/win_x64_profile -GNinja .'
  - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && Tools\CMake\Win32\bin\cmake.exe --build CMake/win_x64_profile'